### PR TITLE
[WIP] Refactor/dashboard

### PR DESCRIPTION
**Pull request by abaicus**

### CODE REVIEW

**Review by abaicus — COMMENTED** [review]
@arinaturcu This looks great! 🚀 


I've left a few things that we should change/can improve. Let me know if you have any questions 👍🏻 


- Let's also remove the `yarn.lock` file as this repository uses npm for CI.
- We have to find a workaround to using ReactHTMLParser as it's more than half of the bundle. We should look into using `dangerouslySetInnerHTML` instead.
image
- Let's make sure we enqueue the CSS for the social sharing icons inside the dashboard by default, and not only when the module is enabled. Otherwise, the icons won't be there when you enable the module: 
image

**Review by abaicus — COMMENTED** [review]
@arinaturcu Great work on this! 🚀🚀🚀 


There are two functionality issues that I found:

- The plugins load in a different order on each page reload inside `obfxDash.plugins
`. Maybe we can make sure we sort the plugins array when we localize it.

- The plugins tab doesn't maintain the current state of the plugin (i.e. if it's installed/activated/deactivated from the interface). It still displays with the initial state if you take an action on the plugins tab and then switch between the tabs. We should make sure we keep that state in the context so we have consistency.

**Comment by cristian-ungureanu** [comment]
@arinaturcu here's what I found:

- [ ] I would keep the position of the checkboxes as it was before, one next to the other instead of one under the other https://vertis.d.pr/qeKpm2 vs https://vertis.d.pr/Z0dtCv
- [ ] This is something that it's not working in the current version but maybe we can implement it. Feel free to ignore it if it's hard to implement. For the Template Directory module do you think we can refresh the page after it's enabled? Otherwise, nothing appears in the menu until you refresh the page. Maybe we can have a general property like "refresh_after_enabled" and set it as true for modules of this kind.
- [ ] Maybe we can make this icon spin https://vertis.d.pr/vgF0jt
- [ ] Please add a comment for all your functions, there are two functions in class-orbit-fox-admin.php without a comment.

Everything else looks really good. I've tested the functionality and everything works like before.

**Comment by cristian-ungureanu** [comment]
@abaicus the plugins load in a different order because that's the intended behavior. https://github.com/Codeinwp/themeisle-companion/blob/master/core/app/class-orbit-fox-admin.php#L327

**Comment by abaicus** [comment]
@cristian-ungureanu Thanks for the clarification 👍🏻

**Comment by arinaturcu** [comment]
@cristian-ungureanu @abaicus Thank you for the feedback! I made the changes you requested, hope everything is fine. :rocket:

**Comment by cristian-ungureanu** [comment]
Thank you @arinaturcu, you did an awesome job here. Everything looks good, I'm gonna merge this PR.

**Pull request merged**
