### PR TITLE
Feat/custom fonts module

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
https://github.com/Codeinwp/neve-pro-addon/issues/919

### CODE REVIEW

**Comment by irinelenache** [comment]
@cristian-ungureanu 

- [ ] when i activate the plugin on a fresh wp instance (no other plugin installed) i get this error -> https://prnt.sc/uvjism  (don't know if otter should/shouldn't be installed)

- [ ] upload buttons don't work, i get this in console:
https://www.loom.com/share/bce0b8d79ea34858b3b38683c4aedff5
using Mozilla, the error is different -> https://prnt.sc/uvjoa3

**Comment by rodica-andronache** [comment]
the same thing with the upload button not working, so it can be tested properly for the moment 
download (1)

I would also suggest we don't make the module active by default, as we did with the Header/Footer scripts which is now loaded everywhere even though is not used

**Comment by cristian-ungureanu** [comment]
@irinelenache when you clone or download obfx, you first need to run "composer install" in the root of the plugin because the composer modules are not added on the repo. That's why you're getting that fatal error.

I've fixed the problem with the upload buttons and made the module not active by default.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu The upload button doesn't work well when you try to edit an already created custom font
https://www.loom.com/share/7ea727f22a1d4adbb4841fa4d94e28e2

**Comment by cristian-ungureanu** [comment]
@rodica-andronache should be fine now

**Comment by rodica-andronache** [comment]
@cristian-ungureanu a small thing, not sure what's causing it, and if it can be fixed https://www.loom.com/share/7b0b1d39932e47f3a149230ed80e2bf4

**Comment by cristian-ungureanu** [comment]
@rodica-andronache fixed it.

**Pull request merged**
