### PR TITLE
Add Font Awesome 5

### LINKED ISSUE #295: Font Awesome 5 support
Given that we already have added Font Awesome 5 to Gutenberg Blocks, we should also add its support to Menu Icons module. I tried doing it in my free time and was successful in doing so.

It works and all, just we have to think of backward compatibility, for which there are two ways of doing it:

1. Just use Font Awesome 5, and run a migration which will replace already saved menu with the new FA prefixes.

2. Just let the old ones go and add a shim of FA4 so that old ones also work, which we can also do because Gutenberg is already enqueuing shim + theme or something else might be using FA4 so it's a better idea.

What do you think? @abaicus

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Added Font Awesome 5 for Menu Icons module, and moved them to /assets/ folder so we can utilize it in multiple modules. Closes #295

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@abaicus Added FA5 for Menu Icons, with shims so they do support older version of Font Awesome too. Would be good to test from your end. Also made a new /assets/ folder for FA and related things that can be shared across modules.

**Comment by radu-themeisle** [comment]
@HardeepAsrani take a look at this issue #323 test out the bumps we hit on the road to implementing FA5, you might have the same issues.
One of the big issues is: What do you do when you have a plugin using v 4.7 (e.g. Elementor or Woocommerce)? You can't really deque everyone's enque of FA 😁

**Comment by HardeepAsrani** [comment]
@radu-themeisle I did try everything out and it worked just fine. Can someone else try and see if I missed something? I'm sure there will be few things I missed but I'm also sure we can implement this with few fixes.

**Comment by radu-themeisle** [comment]
@HardeepAsrani I'll try to help test out today some things that I remember were in conflict

**Comment by radu-themeisle** [comment]
@HardeepAsrani here's how Hestia's contact section looks: http://prntscr.com/mxpryu
As I noted here #323 there are some icons that have different UTF-8 code in v5 which breaks them. Do you have a solution for those cases?

**Comment by HardeepAsrani** [comment]
> Welcome to Jurassic Ninja!
> 
> https://continental-sally.jurassic.ninja will be destroyed in 7 days. Sign out and sign in to get 7 more days.
> 
> WP user: demo SSH: ssh usereed07181@continental-sally.jurassic.ninja
> 
> WP/SSH password: txQ9eKnA0TS6 SSH server path: /srv/users/usereed07181/apps/usereed07181/public/ 

@radu-themeisle Can you see here? The fonts also don't appear in backend for Menu Icons with the current Fonts + Hestia.

**Comment by radu-themeisle** [comment]
Nope, the icons are not visible: http://prntscr.com/mxrywn
In Menu Icons there is an issue which I made a PR for and I'm waiting for it to be reviewed if it's the correct solution: #343 ;

**Comment by selul** [comment]
@radu-themeisle i've merged your PR, is this PR stable to merge?

**Comment by radu-themeisle** [comment]
@selul No, it has no updates and the issues I've spotted are still present

**Comment by selul** [comment]
closing it as stale, we can later on tackle this

**Pull request closed without merging**
