### PR TITLE
Gutenberg blocks

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Everything works but Contact Form block. If an error found, let me know. Keep the console open as things are depreciated in every damn release.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@abaicus Can you look into all the blocks (except Font Awesome and Contact) and give feedback? Some of them have changed a lot, and now they use columns to work better with Gutenberg.

**Comment by abaicus** [comment]
Hey @HardeepAsrani!

The blocks look great so far! There are a few things that didn't work as expected though.

- Sharing icons block doesn't properly display on the front end with icons only - it still shows the name of the social networks.
- After coming back to gutenberg editor again, the accordion and notice blocks say they've been modified externally, also the author block seems to be stuck loading.
image
image
image￼
- The plugin card block doesn't align on the front end.
- Switching the google maps block to satellite and back to road map yields the following error:
￼
image


**A few more suggestions:**
- Add alignment options to sharing icons / notice blocks
- Allow accent color selection to the plugin card block to be able to change the main color.
- The pricing tables could be spaced a bit better on the front end side:
￼
image

- Would it be possible to have a bigger width for the columns blocks? Right now it's restricted to 610px and doesn't really look that good inside the editor
￼
image


Good job on these! They look awesome!

**Comment by ineagu** [comment]
would be nice to see how they look with add_editor_style as well for hestia :D

**Comment by HardeepAsrani** [comment]
@abaicus Thanks for the review. I'll take a look.

And for the last point, there will be a function in Gutenberg for themes to declare the editor width. Right now we can't do much.

**Comment by HardeepAsrani** [comment]
> Sharing icons block doesn't properly display on the front end with icons only - it still shows the name of the social networks.

- Silly mistake. Fixed it.

> After coming back to gutenberg editor again, the accordion and notice blocks say they've been modified externally.

- Fixed.

> The author block seems to be stuck loading.

- Can you see the console for an error? Works just fine for me.

> The plugin card block doesn't align on the front end.

- To quote Gutenberg, "Important: It doesn't work with dynamic blocks yet.

> Switching the google maps block to satellite and back to road map yields the following error:

- Added wrong option. It's `roadmap` and I added `roadtype`.

> Add alignment options to sharing icons / notice blocks

- For sharing icons, added it. However, it won't work in the front-end until they figure out a way.

- Doesn't make sense for Notice Blocks. Who aligns notices?

> Allow accent color selection to the plugin card block to be able to change the main color.

- The idea is to make the blocks simple and allow themes to customize it with CSS. Maybe @selul  can comment if this is needed?

> The pricing tables could be spaced a bit better on the front end side:

- Again, it uses theme styling with pretty much no CSS. Here's how it looks in Hestia:

screen shot 2018-09-29 at 3 23 23 am


> Would it be possible to have a bigger width for the columns blocks? Right now it's restricted to 610px and doesn't really look that good inside the editor

- Noted in the last reply.

@abaicus What do you think?
 
PR on its way.

**Comment by abaicus** [comment]
This seems to work fine, except a few issues that are probably gutenberg related and the posts grid issue I've already told you about. 

image

**Comment by HardeepAsrani** [comment]
@selul Can you check the Post Grid on your side? Can't find the issue.

**Pull request merged**
