### PR TITLE
FEAT: New module Uptime Monitor.

### PR DESCRIPTION
**Pull request by preda-bogdan**
Some Changes to Core files. 
Added new hooks: 
`[module_slug]_activate` -- called when module activates (registered automatically)
`[module_slug]_deactivate` -- called when module activates (registered automatically)
`[module_slug]_before_options_save`
`[module_slug]_after_options_save`

### CODE REVIEW

**Comment by ineagu** [comment]
@preda-bogdan do you need amazon ses details?

**Comment by preda-bogdan** [comment]
@ineagu No, I will need a mailgun or similar service for the mail. For now the server is configured to use some sandbox credentials.

**Comment by ineagu** [comment]
okay, I have sent the info in slack for that since we first need to validate the domain + email address used for sending

**Comment by ineagu** [comment]
@preda-bogdan let me know when you have an update on the smtp thing.

**Comment by abaicus** [comment]
@preda-bogdan Is this ready for merge? 👍 :D

**Pull request merged**
