### PR TITLE
Remove Gutenberg blocks module

### LINKED ISSUE #702: Removing Otter Blocks from Orbit Fox
The idea is to first disable the module for new installs while allowing old installs some time to migrate to Otter plugin itself. And then removing the package altogether.

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
Here's what I did here:
1. The module does not appear if Otter is active or if the current user is new.
2. If the module appears:
    - I added a notice under the module description saying that the module will soon be removed: https://vertis.d.pr/Ky9mKR
    - I added a dismissible notice that is saying you should install Otter: https://vertis.d.pr/J4o8GT.
    - I added Otter at recommended plugins and when you dismiss the notice, it will redirect you to recommended plugins: https://vertis.d.pr/T1LGWT

Closes #702

### CODE REVIEW

**Comment by cristian-ungureanu** [comment]
@irinelenache here's how you should test this:

1. Create two instances on TasteWp.
2. On the first instance get OBFX from wp.org, activate it, and make sure the Gutenberg module is active. Wait 2 minutes and then update OBFX with this version. You should:
- See a notice under the module description saying that the module will soon be removed: https://vertis.d.pr/Ky9mKR
- See a dismissible notice that is saying you should install Otter: https://vertis.d.pr/J4o8GT. When you dismiss the notice, it should take you to the recommended plugins tab.
- When you disable the module and then refresh the page, the module should not appear anymore.
3. On the second instance, install directly this version of OBFX. In this case, you will be seen as a new user and the module should not appear at all.

**Comment by irinelenache** [comment]
@cristian-ungureanu I tried testing by creating an instance with obfx from wp.org, adding some blocks to a post and then updating with this version. The otter module wasn't present anymore in obfx settings and i didn't get any notice. When i checked the post that had the blocks added, they weren't visible anymore.
Can be checked on this instance:
```
 Admin area URL: https://dustyboat.tastewp.com/wp-admin 
 Username: irinel 
 Password: 0D-obIrbd_U 
```

**Comment by cristian-ungureanu** [comment]
Thanks for testing @irinelenache. The problem should be fixed now.

**Comment by irinelenache** [comment]
@cristian-ungureanu tested again and now it works fine, didn't find any problem 👍

**Pull request merged**
