### PR TITLE
[Menu Icons] Custom navwalker overwrites others

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by ineagu** [comment]
with this logic, menu icons feature won't work at all with oceanwp?

**Comment by contactashish13** [comment]
yes, they won't. they won't work with any other theme/plugin that registers a custom walker.

**Comment by ineagu** [comment]
I guess then that the behaviour is not ideal from a UX perspective. Some ideas 👍 

1. when we detect this, disable menu icons by default. If users choose to activate it, we can let them do it without warning.

2. Disable and notify that module is not compatible with the theme.

cc @abaicus

**Comment by contactashish13** [comment]
@ineagu agreed. Maybe a mix of both your ideas would work - disable menu icons by default and add a warning below it. If users want to still enable it, they can do it. What do you think?

**Comment by contactashish13** [comment]
@ineagu @abaicus I've incorporated this approach.

**Comment by abaicus** [comment]
@contactashish13 
Either make it more proeminent by adding the `.chip` class (see image below), or adding an intent modal like we have on the uptime monitor module. To make sure that the user knows even if he doesn't pay attention in the first place. 
image


cc: @ineagu

**Comment by contactashish13** [comment]
@abaicus have added the chip class.

**Pull request merged**
