### PR TITLE
Mystock module fixes

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
- Better error handling when importing images
- Change the dimension of the image from original to large so the import won't take that long

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@cristian-ungureanu 

- [ ] the `Load More Images` button is not clickable while the `Image was inserted in post content` message is displayed ( after an image is imported )

Screenshot (9)

- [ ] And when more images are imported one after the other and more messages `Image was inserted in post content` are displayed at the same time, the last image on the bottom can't be imported, as you can't see the buttons for it, on hover.

Screenshot (10)

- [ ] for any image listed based on any keyword search, I get an error and can't import it

Screenshot (11)

**Comment by cristian-ungureanu** [comment]
Thanks @rodica-andronache, It should work now.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu everything's working well 👍 
I'm just not sure if that z-index is the best solution. The notice is behind other elements, and just part of it is visible, depending on the theme.

Neve
Screenshot 2020-04-24 at 17 28 56


2020
Screenshot 2020-04-24 at 17 29 27

**Comment by cristian-ungureanu** [comment]
@rodica-andronache that notification has z-index 100000, that's how it's implemented in core. I've changed what I've done and now I've put the z-index on the sidebar which shouldn't interfere with anything. It's either that or we remove the notification.

**Comment by rodica-andronache** [comment]
is looking good 👍

**Pull request merged**
