### PR TITLE
Add support to override default icons

### PR DESCRIPTION
**Pull request by suyogyashukla**
Override default Our Focus Widget icons from Child Theme suyogyashukla/Portif#2

### CODE REVIEW

**Comment by ineagu** [comment]
not possible one filter with multiple params ?

cc @rodica-andronache

**Comment by suyogyashukla** [comment]
Not sure how to do that. @rodica-andronache Any ideas? :D

**Comment by ineagu** [comment]
// Accepting two arguments (three possible).
function example_callback( $value, $arg2 ) {
    ...
    return $maybe_modified_value;
}
add_filter( 'hook', 'example_callback', 10, 2 ); // Where $priority is
10, $accepted_args is 2.

**Comment by rodica-andronache** [comment]
@suyogyashukla I changed the filters to have just one, with an extra parameter.

Now, in your child theme you can do something like this:
`add_filter( 'zerif_ourfocus_icon_default_filter','example_callback', 10, 2 );
function example_callback( $arg1, $arg2 ) {

	if( $arg2 == 'first' ) {
               return get_stylesheet_directory_uri() . "/images/first.jpg";
	} elseif( $arg2 == 'second' ) {

		return get_stylesheet_directory_uri() . "/images/second.jpg";
	}
}`

You can find more explanations here: https://gist.github.com/rodica-andronache/42b57f63006466678200feb84f72a82e

**Pull request merged**
